stages:          
    - deploy

    variables:
    $WORDPRESS_FOLDER: /var/www/app.tsteplova.fun/wordpress
    $DEPLOY_USER: runner
    $APP_SERVER: app.tsteplova.fun
    deploy-job:
    stage: deploy
    script:
        - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$APP_SERVER "sudo rm -rf $WORDPRESS_FOLDER*"
        - scp -o StrictHostKeyChecking=no -q -r $CI_PROJECT_DIR/* $DEPLOY_USER@$APP_SERVER:$WORDPRESS_FOLDER;

