---
db_user: wordpress
db_pass: wordpress
db_name: wordpress
mysql_replication_master: db01
mysql_replication_user: my_adm
mysql_replication_user_password: "{{ replicator_psw }}"

mysql_packages:
  - mysql-server
  - python3-mysqldb
mysql_service: mysql
mysql_conf_dir: "/etc/mysql"
